from pydantic import BaseModel, Field


class AgentAskRequest(BaseModel):
    question: str = Field(min_length=1, description="User question for the agent.")
    user_id: str | None = Field(
        default=None,
        description="Optional user id propagated to tool execution context.",
    )
    session_id: str | None = Field(
        default=None,
        description="Optional session id used for tool context.",
    )


class AgentAskResponse(BaseModel):
    status: str = Field(description="Execution status.")
    answer: str = Field(description="Final answer generated by the agent.")
    steps: int = Field(description="Number of loop iterations used.")
    tools_used: list[str] = Field(description="List of tool names called by the agent.")
