from pydantic import BaseModel, Field


class AgentCitation(BaseModel):
    source: str = Field(description="Citation source identifier.")
    doc_id: str = Field(description="Indexed document id.")
    chunk_id: str = Field(description="Indexed chunk id.")
    snippet: str = Field(description="Retrieved text snippet.")
    page_number: int | None = Field(
        default=None,
        description="Optional page number when citation comes from PDF ingestion.",
    )


class AgentAskRequest(BaseModel):
    question: str = Field(min_length=1, description="User question for the agent.")
    doc_id: str = Field(description="Document id used to scope retrieval for this request.")
    session_id: str | None = Field(
        default=None,
        description="Optional session id used for tool context.",
    )


class AgentAskResponse(BaseModel):
    status: str = Field(description="Execution status.")
    answer: str = Field(description="Final answer generated by the agent.")
    steps: int = Field(description="Number of loop iterations used.")
    tools_used: list[str] = Field(description="List of tool names called by the agent.")
    citations: list[AgentCitation] = Field(
        default_factory=list,
        description="Optional citations extracted from retrieved context.",
    )
